name: 'XIKO ART '
favicon: null
layout_spectrum: 0.825729203177616
typography_spectrum: 0.48325718753039837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.581635701470077
  lightness: 0.3423506007529795
  saturation: 0.854126137914136
  rhythmicContrast: 0.5394147615879774
purpose: []
